<?php

namespace App\Models;

use App\Models\Concerns\UsesUuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class OrderPosition extends Model
{
    use UsesUuid;

    protected $table = "orders_positions";

    public $timestamps = false;

    protected $fillable = [
        "product_id",
        "order_id",
        "count"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        parent::creating(function (OrderPosition $orderPosition) {
            if (!isset($orderPosition->count)){
                $orderPosition->count = 1;
            }
        });
    }

    public function product(): belongsTo
    {
        return $this->belongsTo(Product::class);
    }

    public function order(): belongsTo
    {
        return $this->belongsTo(Order::class);
    }
}
